// Generated by CoffeeScript 1.11.1
(function() {
  var changeViewOfFooterByWinSize;

  changeViewOfFooterByWinSize = function() {
    $("footer").removeClass("footerFix");
    if ($(window).height() === $(document).height()) {
      return $("footer").addClass("footerFix");
    } else {
      return $("footer").removeClass("footerFix");
    }
  };

  $(document).ready(function() {
    changeViewOfFooterByWinSize();
    return $(window).resize(function() {
      return changeViewOfFooterByWinSize();
    });
  });

}).call(this);

//# sourceMappingURL=publicScript.js.map
